export const SUBARTICLES_LIST_REQUEST = "SUBARTICLES_LIST_REQUEST";
export const SUBARTICLES_LIST_SUCCESS = "SUBARTICLES_LIST_SUCCESS";
export const SUBARTICLES_LIST_FAIL = "SUBARTICLES_LIST_FAIL";

export const SUBARTICLES_DETAILS_REQUEST = "SUBARTICLES_DETAILS_REQUEST";
export const SUBARTICLES_DETAILS_SUCCESS = "SUBARTICLES_DETAILS_SUCCESS";
export const SUBARTICLES_DETAILS_FAIL = "SUBARTICLES_DETAILS_FAIL";

export const SUBARTICLES_CREATE_REQUEST = "SUBARTICLES_CREATE_REQUEST";
export const SUBARTICLES_CREATE_SUCCESS = "SUBARTICLES_CREATE_SUCCESS";
export const SUBARTICLES_CREATE_FAIL = "SUBARTICLES_CREATE_FAIL";
export const SUBARTICLES_CREATE_RESET = "SUBARTICLES_CREATE_RESET";
export const SUBARTICLES_CREATE = "SUBARTICLES_CREATE";

export const SUBARTICLE_UPDATE_REQUEST = "SUBARTICLE_UPDATE_REQUEST";
export const SUBARTICLE_UPDATE_SUCCESS = "SUBARTICLE_UPDATE_SUCCESS";
export const SUBARTICLE_UPDATE_FAIL = "SUBARTICLE_UPDATE_FAIL";
export const SUBARTICLE_UPDATE_RESET = "SUBARTICLE_UPDATE_RESET";

export const SUBARTICLE_DELETE_REQUEST = "SUBARTICLE_DELETE_REQUEST";
export const SUBARTICLE_DELETE_SUCCESS = "SUBARTICLE_DELETE_SUCCESS";
export const SUBARTICLE_DELETE_FAIL = "SUBARTICLE_DELETE_FAIL";
export const SUBARTICLE_DELETE_RESET = "SUBARTICLE_DELETE_RESET";
